name: wanikani_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.4.0              # HTTP client robusto
  drift: ^2.14.0           # SQLite type-safe
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  logger: ^2.0.0           # Logging estruturado e colorido
  # Networking
  
  # Storage/Cache
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  flutter_secure_storage: ^9.0.0
  
  # Navigation
  go_router: ^13.0.0
  
  # Dependency Injection
  get_it: ^7.6.0
  
  # UI/Theme
  flutter_screenutil: ^5.9.0
  
  # Utilities
  equatable: ^2.0.5        # Value equality
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.0
  url_launcher: ^6.2.0
  package_info_plus: ^5.0.0

flutter:
  uses-material-design: true
  
  # Mock assets para desenvolvimento
  assets:
    - assets/mock/
  
  # Fontes Noto Sans JP para interface japonesa
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 900

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.0
  drift_dev: ^2.14.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.0
  json_serializable: ^6.7.0
  # Code Generation
  
  # Testing
  mocktail: ^1.0.0
